# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FE_traing.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

from TrainingVideoWidget import TrainingVideoWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1319, 710)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 681, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.videoWidget = TrainingVideoWidget(self.gridLayoutWidget)
        self.videoWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoWidget.sizePolicy().hasHeightForWidth())
        self.videoWidget.setSizePolicy(sizePolicy)
        self.videoWidget.setAutoFillBackground(True)
        self.videoWidget.setStyleSheet("videoWidget{background-color:#ffffff;}")
        self.videoWidget.setObjectName("videoWidget")
        self.gridLayout_2.addWidget(self.videoWidget, 2, 4, 2, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(80, 560, 81, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_stopTraining = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_stopTraining.setAutoFillBackground(False)
        self.btn_stopTraining.setStyleSheet("QPushButton{border-image: url(img/stopTraining.png)}")
        self.btn_stopTraining.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/81583/.designer/backup/from TrainingVideoWidget import TrainingVideoWidget"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stopTraining.setIcon(icon)
        self.btn_stopTraining.setObjectName("btn_stopTraining")
        self.gridLayout_3.addWidget(self.btn_stopTraining, 0, 0, 1, 1)
        self.open_camera = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.open_camera.setAutoFillBackground(False)
        self.open_camera.setStyleSheet("QPushButton{border-image: url(img/openCam.png)}")
        self.open_camera.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/81583/.designer/backup/img/openCam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_camera.setIcon(icon1)
        self.open_camera.setObjectName("open_camera")
        self.gridLayout_3.addWidget(self.open_camera, 0, 3, 1, 1)
        self.btn_startTraining = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_startTraining.setAutoFillBackground(False)
        self.btn_startTraining.setStyleSheet("QPushButton{border-image: url(img/startTraining.png)}")
        self.btn_startTraining.setText("")
        self.btn_startTraining.setObjectName("btn_startTraining")
        self.gridLayout_3.addWidget(self.btn_startTraining, 0, 1, 1, 1)
        self.close_camera = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.close_camera.setAutoFillBackground(False)
        self.close_camera.setStyleSheet("QPushButton{border-image: url(img/closeCam.png)}")
        self.close_camera.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/81583/.designer/backup/img/closeCam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_camera.setIcon(icon2)
        self.close_camera.setObjectName("close_camera")
        self.gridLayout_3.addWidget(self.close_camera, 0, 2, 1, 1)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(1100, 520, 201, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.formLayoutWidget)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.horizontalSlider = QtWidgets.QSlider(self.formLayoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(240, 520, 851, 151))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tips_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tips_label.setFont(font)
        self.tips_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tips_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tips_label.setObjectName("tips_label")
        self.gridLayout_5.addWidget(self.tips_label, 0, 1, 1, 1)
        
        self.sEMG_tips_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.sEMG_tips_label.setFont(font)
        self.sEMG_tips_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sEMG_tips_label.setObjectName("sEMG_tips_label")
        self.gridLayout_5.addWidget(self.sEMG_tips_label, 1, 1, 1, 1)

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(680, 0, 701, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cameraLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraLabel.sizePolicy().hasHeightForWidth())
        self.cameraLabel.setSizePolicy(sizePolicy)
        self.cameraLabel.setAutoFillBackground(True)
        self.cameraLabel.setObjectName("cameraLabel")
        self.verticalLayout.addWidget(self.cameraLabel)
        self.btn_more = QtWidgets.QPushButton(self.centralwidget)
        self.btn_more.setGeometry(QtCore.QRect(10, 560, 61, 51))
        self.btn_more.setToolTip("")
        self.btn_more.setAutoFillBackground(False)
        self.btn_more.setStyleSheet("QPushButton{border-image: url(img/more.png)}")
        self.btn_more.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/81583/.designer/backup/more.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_more.setIcon(icon3)
        self.btn_more.setIconSize(QtCore.QSize(40, 40))
        self.btn_more.setCheckable(False)
        self.btn_more.setObjectName("btn_more")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 640, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1319, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "语音提示"))
        self.label_2.setText(_translate("MainWindow", "背景声音"))
        self.tips_label.setText(_translate("MainWindow", "提示文字"))
        self.sEMG_tips_label.setText(_translate("MainWindow", "请确保肌电已连接"))
        self.cameraLabel.setText(_translate("MainWindow", "摄像头"))
        self.pushButton.setText(_translate("MainWindow", "退出"))

