# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Select_win.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1157, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(740, 50, 371, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setStyleSheet("image: url(:/newPrefix/Photo/Class/class0.jpg);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.name0_3 = QtWidgets.QLabel(self.layoutWidget)
        self.name0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.name0_3.setObjectName("name0_3")
        self.horizontalLayout_14.addWidget(self.name0_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        self.last0_3 = QtWidgets.QLabel(self.layoutWidget)
        self.last0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.last0_3.setObjectName("last0_3")
        self.horizontalLayout_15.addWidget(self.last0_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.difficult0_3 = QtWidgets.QLabel(self.layoutWidget)
        self.difficult0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.difficult0_3.setObjectName("difficult0_3")
        self.horizontalLayout_16.addWidget(self.difficult0_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.btn_start_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_start_5.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_start_5.setObjectName("btn_start_5")
        self.horizontalLayout_17.addWidget(self.btn_start_5)
        self.btn_start_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_start_6.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_start_6.setObjectName("btn_start_6")
        self.horizontalLayout_17.addWidget(self.btn_start_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.horizontalLayout_13.setStretch(0, 8)
        self.horizontalLayout_13.setStretch(1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(330, 240, 371, 141))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setStyleSheet("image: url(:/newPrefix/Photo/Class/class0.jpg);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_18.addWidget(self.label_15)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16)
        self.name0_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.name0_4.setAlignment(QtCore.Qt.AlignCenter)
        self.name0_4.setObjectName("name0_4")
        self.horizontalLayout_19.addWidget(self.name0_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_20.addWidget(self.label_17)
        self.last0_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.last0_4.setAlignment(QtCore.Qt.AlignCenter)
        self.last0_4.setObjectName("last0_4")
        self.horizontalLayout_20.addWidget(self.last0_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_21.addWidget(self.label_18)
        self.difficult0_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.difficult0_4.setAlignment(QtCore.Qt.AlignCenter)
        self.difficult0_4.setObjectName("difficult0_4")
        self.horizontalLayout_21.addWidget(self.difficult0_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.btn_start_7 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_start_7.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_start_7.setObjectName("btn_start_7")
        self.horizontalLayout_22.addWidget(self.btn_start_7)
        self.btn_start_8 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_start_8.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_start_8.setObjectName("btn_start_8")
        self.horizontalLayout_22.addWidget(self.btn_start_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_18.addLayout(self.verticalLayout_10)
        self.horizontalLayout_18.setStretch(0, 8)
        self.horizontalLayout_18.setStretch(1, 1)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(740, 240, 371, 141))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_19.setStyleSheet("image: url(:/newPrefix/Photo/Class/class0.jpg);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_23.addWidget(self.label_19)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_24.addWidget(self.label_20)
        self.name0_5 = QtWidgets.QLabel(self.layoutWidget_3)
        self.name0_5.setAlignment(QtCore.Qt.AlignCenter)
        self.name0_5.setObjectName("name0_5")
        self.horizontalLayout_24.addWidget(self.name0_5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_25.addWidget(self.label_21)
        self.last0_5 = QtWidgets.QLabel(self.layoutWidget_3)
        self.last0_5.setAlignment(QtCore.Qt.AlignCenter)
        self.last0_5.setObjectName("last0_5")
        self.horizontalLayout_25.addWidget(self.last0_5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_26.addWidget(self.label_22)
        self.difficult0_5 = QtWidgets.QLabel(self.layoutWidget_3)
        self.difficult0_5.setAlignment(QtCore.Qt.AlignCenter)
        self.difficult0_5.setObjectName("difficult0_5")
        self.horizontalLayout_26.addWidget(self.difficult0_5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.btn_start_9 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_start_9.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_start_9.setObjectName("btn_start_9")
        self.horizontalLayout_27.addWidget(self.btn_start_9)
        self.btn_start_10 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_start_10.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start_10.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_start_10.setObjectName("btn_start_10")
        self.horizontalLayout_27.addWidget(self.btn_start_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_23.addLayout(self.verticalLayout_11)
        self.horizontalLayout_23.setStretch(0, 8)
        self.horizontalLayout_23.setStretch(1, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(330, 430, 371, 141))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_23.setStyleSheet("image: url(:/newPrefix/Photo/Class/class0.jpg);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_28.addWidget(self.label_23)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_29.addWidget(self.label_24)
        self.name0_6 = QtWidgets.QLabel(self.layoutWidget_4)
        self.name0_6.setAlignment(QtCore.Qt.AlignCenter)
        self.name0_6.setObjectName("name0_6")
        self.horizontalLayout_29.addWidget(self.name0_6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_30.addWidget(self.label_25)
        self.last0_6 = QtWidgets.QLabel(self.layoutWidget_4)
        self.last0_6.setAlignment(QtCore.Qt.AlignCenter)
        self.last0_6.setObjectName("last0_6")
        self.horizontalLayout_30.addWidget(self.last0_6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_31.addWidget(self.label_26)
        self.difficult0_6 = QtWidgets.QLabel(self.layoutWidget_4)
        self.difficult0_6.setAlignment(QtCore.Qt.AlignCenter)
        self.difficult0_6.setObjectName("difficult0_6")
        self.horizontalLayout_31.addWidget(self.difficult0_6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.btn_start_11 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.btn_start_11.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start_11.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_start_11.setObjectName("btn_start_11")
        self.horizontalLayout_32.addWidget(self.btn_start_11)
        self.btn_start_12 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.btn_start_12.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start_12.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_start_12.setObjectName("btn_start_12")
        self.horizontalLayout_32.addWidget(self.btn_start_12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_28.addLayout(self.verticalLayout_12)
        self.horizontalLayout_28.setStretch(0, 8)
        self.horizontalLayout_28.setStretch(1, 1)
        self.layoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(740, 430, 371, 141))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_27.setStyleSheet("image: url(:/newPrefix/Photo/Class/class0.jpg);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_33.addWidget(self.label_27)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_34.addWidget(self.label_28)
        self.name0_7 = QtWidgets.QLabel(self.layoutWidget_5)
        self.name0_7.setAlignment(QtCore.Qt.AlignCenter)
        self.name0_7.setObjectName("name0_7")
        self.horizontalLayout_34.addWidget(self.name0_7)
        self.verticalLayout_13.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_35.addWidget(self.label_29)
        self.last0_7 = QtWidgets.QLabel(self.layoutWidget_5)
        self.last0_7.setAlignment(QtCore.Qt.AlignCenter)
        self.last0_7.setObjectName("last0_7")
        self.horizontalLayout_35.addWidget(self.last0_7)
        self.verticalLayout_13.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_36.addWidget(self.label_30)
        self.difficult0_7 = QtWidgets.QLabel(self.layoutWidget_5)
        self.difficult0_7.setAlignment(QtCore.Qt.AlignCenter)
        self.difficult0_7.setObjectName("difficult0_7")
        self.horizontalLayout_36.addWidget(self.difficult0_7)
        self.verticalLayout_13.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.btn_start_13 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.btn_start_13.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start_13.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_start_13.setObjectName("btn_start_13")
        self.horizontalLayout_37.addWidget(self.btn_start_13)
        self.btn_start_14 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.btn_start_14.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start_14.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_start_14.setObjectName("btn_start_14")
        self.horizontalLayout_37.addWidget(self.btn_start_14)
        self.verticalLayout_13.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_33.addLayout(self.verticalLayout_13)
        self.horizontalLayout_33.setStretch(0, 8)
        self.horizontalLayout_33.setStretch(1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 301, 641))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Avatar = QtWidgets.QLabel(self.layoutWidget1)
        self.Avatar.setMinimumSize(QtCore.QSize(0, 0))
        self.Avatar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Avatar.setStyleSheet("image: url(:/newPrefix/Photo/Avatar/avatar1.jpg);")
        self.Avatar.setText("")
        self.Avatar.setPixmap(QtGui.QPixmap("../../../admin/Pictures/知乎/图片/2019-04-13 05_06_45.jpg"))
        self.Avatar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Avatar.setObjectName("Avatar")
        self.horizontalLayout.addWidget(self.Avatar)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.id_label = QtWidgets.QLabel(self.layoutWidget1)
        self.id_label.setAlignment(QtCore.Qt.AlignCenter)
        self.id_label.setObjectName("id_label")
        self.verticalLayout.addWidget(self.id_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.btn_integral = QtWidgets.QLabel(self.layoutWidget1)
        self.btn_integral.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_integral.setObjectName("btn_integral")
        self.horizontalLayout_2.addWidget(self.btn_integral)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(124, 228, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_5.addWidget(self.pushButton_4)
        self.btn_logout = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout_5.addWidget(self.btn_logout)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(330, 50, 371, 141))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setStyleSheet("image: url(:/newPrefix/Photo/Class/class_example.PNG);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.name0 = QtWidgets.QLabel(self.layoutWidget2)
        self.name0.setAlignment(QtCore.Qt.AlignCenter)
        self.name0.setObjectName("name0")
        self.horizontalLayout_4.addWidget(self.name0)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.last0 = QtWidgets.QLabel(self.layoutWidget2)
        self.last0.setAlignment(QtCore.Qt.AlignCenter)
        self.last0.setObjectName("last0")
        self.horizontalLayout_5.addWidget(self.last0)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.difficult0 = QtWidgets.QLabel(self.layoutWidget2)
        self.difficult0.setAlignment(QtCore.Qt.AlignCenter)
        self.difficult0.setObjectName("difficult0")
        self.horizontalLayout_6.addWidget(self.difficult0)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_start_2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_start_2.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_start_2.setObjectName("btn_start_2")
        self.horizontalLayout_3.addWidget(self.btn_start_2)
        self.btn_start = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_start.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_start.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_3.addWidget(self.btn_start)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.horizontalLayout_7.setStretch(0, 8)
        self.horizontalLayout_7.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1157, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_12.setText(_translate("MainWindow", "Name"))
        self.name0_3.setText(_translate("MainWindow", "？？"))
        self.label_13.setText(_translate("MainWindow", "时长"))
        self.last0_3.setText(_translate("MainWindow", "？？"))
        self.label_14.setText(_translate("MainWindow", "难度"))
        self.difficult0_3.setText(_translate("MainWindow", "？？"))
        self.btn_start_5.setText(_translate("MainWindow", "收藏"))
        self.btn_start_6.setText(_translate("MainWindow", "训练"))
        self.label_16.setText(_translate("MainWindow", "Name"))
        self.name0_4.setText(_translate("MainWindow", "？？"))
        self.label_17.setText(_translate("MainWindow", "时长"))
        self.last0_4.setText(_translate("MainWindow", "？？"))
        self.label_18.setText(_translate("MainWindow", "难度"))
        self.difficult0_4.setText(_translate("MainWindow", "？？"))
        self.btn_start_7.setText(_translate("MainWindow", "收藏"))
        self.btn_start_8.setText(_translate("MainWindow", "训练"))
        self.label_20.setText(_translate("MainWindow", "Name"))
        self.name0_5.setText(_translate("MainWindow", "？？"))
        self.label_21.setText(_translate("MainWindow", "时长"))
        self.last0_5.setText(_translate("MainWindow", "？？"))
        self.label_22.setText(_translate("MainWindow", "难度"))
        self.difficult0_5.setText(_translate("MainWindow", "？？"))
        self.btn_start_9.setText(_translate("MainWindow", "收藏"))
        self.btn_start_10.setText(_translate("MainWindow", "训练"))
        self.label_24.setText(_translate("MainWindow", "Name"))
        self.name0_6.setText(_translate("MainWindow", "？？"))
        self.label_25.setText(_translate("MainWindow", "时长"))
        self.last0_6.setText(_translate("MainWindow", "？？"))
        self.label_26.setText(_translate("MainWindow", "难度"))
        self.difficult0_6.setText(_translate("MainWindow", "？？"))
        self.btn_start_11.setText(_translate("MainWindow", "收藏"))
        self.btn_start_12.setText(_translate("MainWindow", "训练"))
        self.label_28.setText(_translate("MainWindow", "Name"))
        self.name0_7.setText(_translate("MainWindow", "？？"))
        self.label_29.setText(_translate("MainWindow", "时长"))
        self.last0_7.setText(_translate("MainWindow", "？？"))
        self.label_30.setText(_translate("MainWindow", "难度"))
        self.difficult0_7.setText(_translate("MainWindow", "？？"))
        self.btn_start_13.setText(_translate("MainWindow", "收藏"))
        self.btn_start_14.setText(_translate("MainWindow", "训练"))
        self.label.setText(_translate("MainWindow", "用户名:"))
        self.id_label.setText(_translate("MainWindow", "Admin"))
        self.label_2.setText(_translate("MainWindow", "运动积分："))
        self.btn_integral.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "参与过的课程"))
        self.pushButton_2.setText(_translate("MainWindow", "收藏的课程"))
        self.pushButton_3.setText(_translate("MainWindow", "课程主页"))
        self.pushButton_4.setText(_translate("MainWindow", "个人设置"))
        self.btn_logout.setText(_translate("MainWindow", "退出"))
        self.label_5.setText(_translate("MainWindow", "Name"))
        self.name0.setText(_translate("MainWindow", "事例"))
        self.label_6.setText(_translate("MainWindow", "时长"))
        self.last0.setText(_translate("MainWindow", "3：54"))
        self.label_7.setText(_translate("MainWindow", "难度"))
        self.difficult0.setText(_translate("MainWindow", "II"))
        self.btn_start_2.setText(_translate("MainWindow", "收藏"))
        self.btn_start.setText(_translate("MainWindow", "训练"))
import Avatar_rc
import class_rc
